#define CHPRIO 0
#define CONS_WRITE 1
#define CONS_READ 2
#define CONS_ECHO 3
#define EXIT 4
#define GETPID 5
#define GETPRIO 6
#define KILL 7
#define PCOUNT 8
#define PCREATE 9
#define PDELETE 10
#define PRECEIVE 11
#define PRESET 12
#define PSEND 13
#define CLOCK_SETTINGS 14
#define CURRENT_CLOCK 15
#define WAIT_CLOCK 16
#define START 17
#define WAITPID 18
#define SYS_INFO 19
#define STRNCMP 20
#define STRLEN 21
#define STRNCPY 22
#define MEMSET 23
#define SAFE_PRINTF 24
#define CONS_GETS 25
#define ASSERT_FAILED 26
#define RANDSHORT 27
#define SETSEED 28
#define RAND 29
#define DIV64 30
#define TEST_IT 31

void traitant_appels_systeme(uint32_t args[]);
void traitant_IT_49();
